/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IncubationRouteImport } from './routes/incubation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramsInformationTechnologyRouteImport } from './routes/programs.information-technology'
import { Route as ProgramsDataScienceRouteImport } from './routes/programs.data-science'
import { Route as ProgramsCrmRouteImport } from './routes/programs.crm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IncubationRoute = IncubationRouteImport.update({
  id: '/incubation',
  path: '/incubation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsInformationTechnologyRoute =
  ProgramsInformationTechnologyRouteImport.update({
    id: '/programs/information-technology',
    path: '/programs/information-technology',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgramsDataScienceRoute = ProgramsDataScienceRouteImport.update({
  id: '/programs/data-science',
  path: '/programs/data-science',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCrmRoute = ProgramsCrmRouteImport.update({
  id: '/programs/crm',
  path: '/programs/crm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/incubation': typeof IncubationRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/programs/crm': typeof ProgramsCrmRoute
  '/programs/data-science': typeof ProgramsDataScienceRoute
  '/programs/information-technology': typeof ProgramsInformationTechnologyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/incubation': typeof IncubationRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/programs/crm': typeof ProgramsCrmRoute
  '/programs/data-science': typeof ProgramsDataScienceRoute
  '/programs/information-technology': typeof ProgramsInformationTechnologyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/contact': typeof ContactRoute
  '/incubation': typeof IncubationRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/programs/crm': typeof ProgramsCrmRoute
  '/programs/data-science': typeof ProgramsDataScienceRoute
  '/programs/information-technology': typeof ProgramsInformationTechnologyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code-of-conduct'
    | '/contact'
    | '/incubation'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/programs/crm'
    | '/programs/data-science'
    | '/programs/information-technology'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code-of-conduct'
    | '/contact'
    | '/incubation'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/programs/crm'
    | '/programs/data-science'
    | '/programs/information-technology'
  id:
    | '__root__'
    | '/'
    | '/code-of-conduct'
    | '/contact'
    | '/incubation'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/programs/crm'
    | '/programs/data-science'
    | '/programs/information-technology'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  ContactRoute: typeof ContactRoute
  IncubationRoute: typeof IncubationRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  ProgramsCrmRoute: typeof ProgramsCrmRoute
  ProgramsDataScienceRoute: typeof ProgramsDataScienceRoute
  ProgramsInformationTechnologyRoute: typeof ProgramsInformationTechnologyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incubation': {
      id: '/incubation'
      path: '/incubation'
      fullPath: '/incubation'
      preLoaderRoute: typeof IncubationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/information-technology': {
      id: '/programs/information-technology'
      path: '/programs/information-technology'
      fullPath: '/programs/information-technology'
      preLoaderRoute: typeof ProgramsInformationTechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/data-science': {
      id: '/programs/data-science'
      path: '/programs/data-science'
      fullPath: '/programs/data-science'
      preLoaderRoute: typeof ProgramsDataScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/crm': {
      id: '/programs/crm'
      path: '/programs/crm'
      fullPath: '/programs/crm'
      preLoaderRoute: typeof ProgramsCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  ContactRoute: ContactRoute,
  IncubationRoute: IncubationRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  ProgramsCrmRoute: ProgramsCrmRoute,
  ProgramsDataScienceRoute: ProgramsDataScienceRoute,
  ProgramsInformationTechnologyRoute: ProgramsInformationTechnologyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
